import type { Product } from '@/types'

export const PRODUCTS: Omit<Product, 'created_at' | 'updated_at'>[] = [
  /* ── Skin Boosters ─────────────────────────────────────── */
  {
    id: '1',
    slug: 'nctf-boost-135ha',
    name_en: 'NCTF Boost 135 HA',
    name_ko: 'NCTF 부스트 135 HA',
    category: '스킨부스터',
    description: '60가지 활성 성분(12 비타민·24 아미노산·6 효소·5 핵산·6 미네랄)이 피부 세포에 전달하는 완벽한 영양 복합체. 프랑스 Fillmed 정식 공급 제품.',
    price: 0,
    price_original: null,
    emoji: '💉',
    image_url: null,
    gradient_bg: 'linear-gradient(135deg, #1A3055 0%, #2B5080 100%)',
    badges: ['FLAGSHIP', 'CE MARKED'],
    in_stock: true,
    stock_qty: 100,
    sort_order: 1,
    is_active: true,
  },
  {
    id: '2',
    slug: 're2o',
    name_en: 'Re2O (Retino-Filler)',
    name_ko: '리투오 (레티노-필러)',
    category: '스킨부스터',
    description: '레티놀 캡슐화 기술로 피부 속 깊이 전달, 노화 방지 및 피부 재생을 돕는 Fillmed 스킨부스터.',
    price: 0,
    price_original: null,
    emoji: '🔬',
    image_url: null,
    gradient_bg: 'linear-gradient(135deg, #2B5080 0%, #4A7CB5 100%)',
    badges: ['Fillmed'],
    in_stock: true,
    stock_qty: 100,
    sort_order: 2,
    is_active: true,
  },
  {
    id: '3',
    slug: 'inhilo-plus',
    name_en: 'INHILO+',
    name_ko: '인힐로+',
    category: '스킨부스터',
    description: '혁신적인 NAHYCO® 기술 기반 고농도 히알루론산 스킨부스터. 피부 전체 리모델링.',
    price: 0,
    price_original: null,
    emoji: '✨',
    image_url: null,
    gradient_bg: 'linear-gradient(135deg, #3A6B9A 0%, #5B8DC0 100%)',
    badges: ['PREMIUM'],
    in_stock: true,
    stock_qty: 100,
    sort_order: 3,
    is_active: true,
  },
  /* ── Dermal Fillers ────────────────────────────────────── */
  {
    id: '4',
    slug: 'art-filler-universal',
    name_en: 'Art Filler Universal',
    name_ko: '아트 필러 유니버설',
    category: '더말필러',
    description: 'Vivacy Art Filler 시리즈. BELOTERO® 기술의 특허 받은 IPN-Like Technology™ 적용, 자연스러운 볼륨 보충.',
    price: 0,
    price_original: null,
    emoji: '💫',
    image_url: null,
    gradient_bg: 'linear-gradient(135deg, #C6A052 0%, #E0C07A 100%)',
    badges: ['Vivacy', 'CE MARKED'],
    in_stock: true,
    stock_qty: 100,
    sort_order: 4,
    is_active: true,
  },
  {
    id: '5',
    slug: 'architech-30',
    name_en: 'ARCHITECH 30',
    name_ko: '아키텍 30',
    category: '더말필러',
    description: '30mg/ml 고농도 히알루론산 필러. 깊은 주름 교정 및 얼굴 윤곽 개선에 특화된 프리미엄 필러.',
    price: 0,
    price_original: null,
    emoji: '🌟',
    image_url: null,
    gradient_bg: 'linear-gradient(135deg, #B8922A 0%, #D4AD50 100%)',
    badges: ['프리미엄'],
    in_stock: true,
    stock_qty: 100,
    sort_order: 5,
    is_active: true,
  },
  /* ── Medical Devices ───────────────────────────────────── */
  {
    id: '6',
    slug: 'hycoox-injector',
    name_en: 'HYCOOX Auto Injector',
    name_ko: '하이쿡스 자동 인젝터',
    category: '의료기기',
    description: '정밀한 주입량 제어가 가능한 자동 인젝터. 스킨부스터 시술의 효율성과 균일성을 극대화합니다.',
    price: 0,
    price_original: null,
    emoji: '⚙️',
    image_url: null,
    gradient_bg: 'linear-gradient(135deg, #374151 0%, #6B7280 100%)',
    badges: ['의료기기'],
    in_stock: true,
    stock_qty: 50,
    sort_order: 6,
    is_active: true,
  },
  /* ── Dermocosmetics ────────────────────────────────────── */
  {
    id: '7',
    slug: 'fillmed-skin-perfect',
    name_en: 'Fillmed Skin Perfusion',
    name_ko: '필메드 스킨 퍼퓨전',
    category: '더마코스메틱',
    description: 'Fillmed 공식 홈케어 라인. 시술 후 피부 재생과 유지를 위한 병원 전용 더마코스메틱.',
    price: 0,
    price_original: null,
    emoji: '🌿',
    image_url: null,
    gradient_bg: 'linear-gradient(135deg, #4A7C59 0%, #6BA07A 100%)',
    badges: ['Fillmed', '홈케어'],
    in_stock: true,
    stock_qty: 100,
    sort_order: 7,
    is_active: true,
  },
]

export const CATEGORIES = ['전체', '스킨부스터', '더말필러', '의료기기', '더마코스메틱'] as const
